name: Release

on:
  push:
    tags:
      - '*'

jobs:
  style-check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: golangci-lint
        if: github.event_name == 'pull_request'
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.49
      - name: install clang-format
        run: sudo apt update && sudo apt install -y clang-format
      - name: Code check
        run: make lint-c
      - name: Helm check
        run: make helm-ci
  compile-ebpf-test:
    runs-on: ubuntu-20.04
    needs: [style-check]
    steps:
      - uses: actions/checkout@v4
      - name: make
        run: make compile
  go-unit-test:
    runs-on: ubuntu-20.04
    needs: [style-check]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: Test
        run: go test -v ./...
  docker-build:
    runs-on: ubuntu-latest
    needs: [compile-ebpf-test, go-unit-test]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login Github Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/merbridge/merbridge
            merbridge/merbridge
          tags: |
            type=semver,pattern={{version}}

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
